### ISSUE TITLE
Another way to brick a Wii U with Coldboot Haxchi

### ISSUE THREAD

**Issue by ghost** [Plailect/Guide_WiiU#100]
You should add a warning on the CBHC page saying that you should not install a pirated version of the DS Virtual Console Game used to install Haxchi, due to the pirated version of the DS VC game overwriting the existing Legit version and since you need CFW to launch Pirated Games, CBHC will be unable to launch causing a Brick.

**Comment by Plailect** [comment]
I thought this went without saying, but you're right that I should say it.

**Comment by ghost** [comment]
It's pretty obvious to people that have experience with CFW, but since this guide has more appeal to the noobie and they know next to nothing about CFW so it's best to warn them before they accidently brick their consoles.

**Comment by ghost** [comment]
BTW thanks for this and the 3DS Guide, i successfully installed CFW on my 3DS and Wii U without any issues, keep up the good work man.
