### ISSUE TITLE
Wup Installer GX2 channel's zip contents use a different file name now

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#116]
Been seeing a lot of people ask the same question about a specific step on the guide. Here's what someone said
"So i'm on the get-started portion step 12 and it's asking me to copy the WUP_Installer_GX2 folder from the ZIP but it's not the same file name, is it ok?"

So they're referring to the wup installer gx2 channel. The folder within the zip is renamed these days and the guide mentions a slightly different name. It actually gets people stuck more often than I'd think. Thought I'd submit this to put a stop to it.

**Comment by aguzman7338** [comment]
Can confirm, just got stuck on this. Should I rename it?
