### ISSUE TITLE
Change the SD card allocation size recommendation to 32 kb

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#120]
As the guide stands now, it suggests that users format their SD card with 64 kb allocation size. But that is known to cause issues when installing larger sized backups. Wup Installer GX2 will freeze during installation due to this. On the assistance channel we always recommend 32 KB allocation size, much like the 3DS. Users no longer have this issue in the end, there is no need for 64 KB allocation size for the wiiu SD card.

**Comment by Lost-gamer** [comment]
There is still one line to fix in get-started.txt:
> If you need to format an SD card on Windows, do not use the built in formatter or it may cause issues. Use [guiformat](http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm) instead and set to an Allocation Unit Size of 64KB.

**Comment by Plailect** [comment]
Fixed
