### ISSUE TITLE
<code> blocks in subbullets are hard to read

### ISSUE THREAD

**Issue by briaguya** [Plailect/Guide_WiiU#122]
\<code> blocks in the at the second level are quite hard to read:

![image](https://user-images.githubusercontent.com/6384156/37436642-d5864726-27b6-11e8-8215-5fec47824bbf.png)

They're currently being set to .75em
![image](https://user-images.githubusercontent.com/6384156/37436806-d474ca14-27b7-11e8-90ae-b2c40dadabcc.png)
Which appears to be [type-size-6](https://github.com/Plailect/Guide_WiiU/blob/8f39bb170252ef026e5f6799e41b73cd31f5899d/_sass/minimal-mistakes/_variables.scss#L41).

When set to 1em ([type-size-5](https://github.com/Plailect/Guide_WiiU/blob/8f39bb170252ef026e5f6799e41b73cd31f5899d/_sass/minimal-mistakes/_variables.scss#L40)), it's quite a bit easier to read:
![image](https://user-images.githubusercontent.com/6384156/37436886-3cd2fe28-27b8-11e8-9d95-47e6d3d26f53.png)

**Comment by Plailect** [comment]
Setting them at a CSS level would change too much other stuff, though I guess I could perhaps edit the style of just that instance.
