### ISSUE TITLE
config.txt and config.ini issues

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#134]
First lets talk about config.ini. Clicking on it leads to "Page not found", and right clicking it and choosing save link as leads to "file not found on server". 

Next lets talk about config.txt. This one could be downloaded if you right click it and save link as. But the guide doesn't instruct this so a newcomer won't know how to save this file. Clicking on it just opens the .txt and would lead to confusion. 

A solution could be to add them into zips, or maybe even one zip for both. That way it's an easy download. If you don't do the zip idea, you could add text on the side that says (Right click, save link as) to make it more clear how to obtain the file.

**Comment by Plailect** [comment]
Missed a `git add` on `config.ini`, hense the missing file. Also the text files just need a download attribute (as is used in Guide_3DS).

**Comment by MattKimura** [comment]
Ah okay never mind this issue, as long as you're aware of them. Wanted to make sure that it was easy to download those without doing anything special.
