### ISSUE TITLE
Get started page links to two wup installers, and both have the same file name

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#138]
The get started page mentions to download Wup installer GX2 hombrew launcher, and channel version. However the download to both of these is a zip file with the same exact file name so it confused someone who pointed it out to me. its hard to distinguish both of them. 

------------------------------------------------
(The following text is just a personal opinion about wup installer gx2 channel)

As a side note, I really don't think the channel version is necessary enough to warrant having users follow it as a necessary step in the guide. I always see users become confused by it when it comes to setting it up, or even using it once installed since it requires CFW. To me its more of a CBHC thing rather than regular haxchi or mocha users. For the majority of homebrew apps you'll be launching them from homebrew launcher anyways. It's not that much more of a shortcut, plus you can always add wup installer as a button shortcut to the haxchi config which wouldn't require cfw to use. Overall the channel version of wup installer just adds extra steps, is usually confusing to newcomers, and it's not much of a difference of just launching it from HBL like everything else. Why have a shortcut for one app when there isnt a shortcut for other apps. Regular haxchi users don't always have cfw enabled so its kinda needless to launch cfw just to boot wup installer when you can just boot HBL then wup installer. If the user even needs CFW for installing content in wup installer, its pretty much pirated content such as DLC.

Here's how you hack a Wiiu:
Method A -  Put files on SD, Buy DS VC game and install haxchi over it and you're done you now have an entrypoint with haxchi.
Method B - Put files on SD card and you're done, the browser is your entrypoint but not recommended.

CFW isn't something that the user always needs enabled, and it's not the ultimate end goal of setting up a wiiu. Setting up a homebrew entrypoint is the end goal rather than CFW so once you do that you are done. Wup installer gx2 channel isn't a needed step in the process imo. Which is why I'd save that only for CBHC users, people who use CFW constantly. Also a personal gripe, calling it patched sysnand as if trying to differentiate from rednand but rednand isnt used anymore. A newcomer does not know what sysnand is. End of rant

**Comment by Plailect** [comment]
I'll think about this. Also, "patched sysnand" was removed already for the exact reason you mentioned.
