### ISSUE TITLE
suggestion - NAND Backup before Coldboot Haxchi 

### ISSUE THREAD

**Issue by NaruZosa** [Plailect/Guide_WiiU#150]
Hi, just a suggestion, but I think that a NAND backup should be recommended before installing coldboot haxchi. If I recall correctly, coldboot haxchi is the only step with any real possibility of bricking (although only due to user error) and if following the guide step by step, if someone stuffs up their coldboot haxchi install they have no NAND backup to restore to.

**Comment by Plailect** [comment]
NAND backups require very large SD cards on some systems and take hours to complete. So far I haven't heard of any bricks caused by the installer, so it's perfectly reasonable to keep the NAND backup as it is (an optional post-CBHC step).

**Comment by NaruZosa** [comment]
I respectfully disagree. While it isn't common and is due to user error, most occurrences of bricking are caused by a mistake while installing CBHC when the user doesn't read the steps properly.

I'm getting this info from: http://www.wiiubru.com/rip/


As you can see, the majority of them bricked due to stuffing up CBHC and didn't have a NAND backup.

I think that moving the step to be earlier but only for those following CBHC and still having it as optional could potentially save some Wii U consoles if the user doesn't read the steps properly.

I understand that the sort of user to not read steps properly is also likely to skip the optional step, but I doubt that's the case for all of them. If it saves just a few switches by moving an optional step to be earlier, only for those installing CBHC and still having it as an optional but recommended step, I think it's worth seriously considering.

**Comment by Plailect** [comment]
Okay that's fair, I'll change it.
