### ISSUE TITLE
Confusing zip reference

### ISSUE THREAD

**Issue by ISSOtm** [Plailect/Guide_WiiU#172]
A mention of a "payload zip" is made [here](https://github.com/hacks-guide/Guide_WiiU/blob/c3a83376dd216d057bb9eabaf066389ee41ca620/_pages/en_US/get-started.txt#L53); but which one of the 11 zips is it? The word "payload" doesn't appear earlier.

**Comment by Plailect** [comment]
It's referring to [wiiu-env/homebrew_launcher_installer](https://github.com/wiiu-env/homebrew_launcher_installer/releases/latest) which calls itself `payload.zip` in the releases. I'll make this more explicit though

**Comment by Plailect** [comment]
https://github.com/hacks-guide/Guide_WiiU/pull/175
