### ISSUE TITLE
Site just went down

### ISSUE THREAD

**Issue by FOSSforlife** [Plailect/Guide_WiiU#199]
Did the URL change? I was on wiiu.hacks.guide a few minutes ago and now it's down. I'm assuming it has to do with this last [commit](https://github.com/hacks-guide/Guide_WiiU-OLD/commit/26a149d7f2b15acb7ef6f20ccba2a58381ead5ae).

**Comment by ihaveamac** [comment]
It's being replaced and will be the new home of https://wiiuguide.xyz/ soon.
