### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by gatesphere** [Plailect/Guide_WiiU#4]
Going through this and noticing a few things:

  - On page "Get Started", there's no mention of placing the homebrew_launcher.elf in the wiiu/apps/homebrew_launcher directory.  This is kind of important, as it makes loading the homebrew launcher from loadiine.ovh impossible.
  - On the "Homebrew Launcher" page: 

    `Ensure that the drop down box shows “Homebrew Launcher…”, then press “Submit”`

    This should note that it needs to match the version of Homebrew Launcher.elf you have on the SD card, else it fails.

  - On both of the "Mocha CFW" pages, the following options aren't in the Mocha menu in v0.2 (latest):
    ```
    SEEPROM redirection: on
    OTP redirection: on
    Use syshax.xml (coldboothax): off
    ```

**Comment by curtisy1** [comment]
Regarding the Mocha options, they appear when you select redNAND to be on.
The rest should be fixed in the latest upstream (if my changes appear
there, cause my Github is somehow glitching right now)

Jacob Peck <notifications@github.com> schrieb am Fr., 10. März 2017, 15:14:

**Comment by gatesphere** [comment]
Well.  That's weird.  Because I certainly set up RedNAND with Mocha v0.2 last night, and those options definitely did not appear.

I'll give it another go, I suppose...

**Comment by curtisy1** [comment]
I'll see if I can get the options again when I get home. Might be that it's not as easy as I described it, but it certainly was with the Fat32 Mocha build and the codebase didn't change.

Thanks for the suggestions though!

**Comment by Plailect** [comment]
The option is definitely available. Weird...
