### ISSUE TITLE
Use cIOS beta 52 if the user plans on using an SD card for Wii games

### ISSUE THREAD

**Issue by ghost** [Plailect/Guide_WiiU#53]
According to Flump on Discord and with my own experience with a user, beta 53 has a known bug for SD card when it comes to loading Wii games. What'll happen if the user uses beta 53 is that when you launch the Wii game, it will return to the home menu. As soon as you reinstall cIOS with beta 52, the games launch just fine from SD. Some users like to have a USB HDD for Wii U, while using their SD card for vWii which is a nice setup where you never have to remove anything. 

It shoud be noted to use beta 52 instead if using an SD card. I'm not sure what beta 53 offers or if it affects USB HDD's. But with what Flump said, it's an issue with SD card.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide_WiiU/pull/66
