### ISSUE TITLE
Wup Installer GX2 channel needs to be installed on USB

### ISSUE THREAD

**Issue by ghost** [Plailect/Guide_WiiU#56]
In the guide, it has the user install Wup Installer GX2 to the NAND. But does not mention that if the user is using a USB HDD, to install to that instead. Wup Installer GX2 will not launch if it's not installed on a USB HDD if one is connected. Other than that if no USB HDD is plugged in, it'll work from NAND. 

Here's the step: https://wiiu.guide/homebrew-launcher-(channel)

Also having a channel for Wup Installer is something completely optional and shouldn't be a requirement. It even needs CFW before you can use it in which it would mostly benefit CBHC users. Non CBHC users are not gonna launch CFW just to use the Wup Installer GX2 channel. It does not take long to boot up Homebrew Launcher and Wup Installer GX2 at all.

**Comment by Plailect** [comment]
There's no reason not to install the channel for non-CBHC users. They can always just use the Homebrew Launcher version if that's more convenient for them.
