### ISSUE TITLE
hid_to_vpad link takes you to source code of a unstable release

### ISSUE THREAD

**Issue by ep3p** [Plailect/Guide_WiiU#73]
In https://wiiu.guide/get-started , the link for hid_to_vpad takes you to only the source code of the latest release. 

As Matt Kimura appointed in the Discord channel, it should use instead the link https://github.com/Maschell/hid_to_vpad/releases

**Comment by ghost** [comment]
In general the nightly releases work just fine. But if you want to link to one specific version just to avoid a possible broken nightly in the future, you can do that as well.
