### ISSUE TITLE
Misleading info about Wup Installer GX2 channel

### ISSUE THREAD

**Issue by MattKimura** [Plailect/Guide_WiiU#87]
This one isn't due to recent changes to the guide, I noticed this one for quite a while and someone pointed it out.
Take a look here: http://prntscr.com/ga786t

So basically this tells the user that it can only ever be installed to a USB. What it means to say is "It must be installed to your USB device if you have one inserted, else it can be installed to NAND"

Something along those lines. Wup Installer GX2 channel works on NAND, but it must be on USB IF you have a USB.

**Comment by Plailect** [comment]
This was fixed
